training:
  epochs: 1
  batch_size: 64
  learning_rate: 0.0001
  betas: [0.9, 0.999]
  run_name: "Autocasting"
  autocast: True
testing: 
data:
  dataset: "tiny-imagenet-200"
api:
  model: srgan-generator-baseline
note: "Autocasted training."